version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-idp
    ports:
      - "8080:8080" # Porta de acesso ao Keycloak
    environment:
      # Variáveis para a conexão com o banco de dados PostgreSQL
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=123456
      # Usuário e senha do administrador inicial
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=123456
      # Configurações de inicialização do Keycloak
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start-dev # Modo de desenvolvimento (não recomendado para produção)
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    depends_on:
      - keycloak-db
    restart: always

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      # Variáveis para configurar o banco de dados
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always